#!/usr/bin/env bash
# We're trying to understand 301 moved permanently(redirection)

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

replacement_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/OlaiyaO permanent;"

sudo sed -i "s/server_name _;$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
