#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configures HAProxy to route traffic to web-01 and web-02 servers
# Uses a round-robin algorithm for load balancing
# Ensures HAProxy can be managed via an init script

# Update package repositories
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Configure HAProxy
haproxy_config="
frontend JBfrontend
        bind *:80
        mode http
        default_backend JBbackend

backend JBbackend
        balance roundrobin
        server 530653-web-01 54.237.115.176:80 check
        server 530653-web-02 54.234.13.131:80 check
"
echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to start with the system
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Test HAProxy configuration file syntax
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart
