#!/usr/bin/env bash

# creating backups and compressing databases

day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

sudo mysqldump --all-databases -u root --password="" > backup.sql
tar -czvf "$file_name" backup.sql
