#!/usr/bin/env bash
# Nginx port 80 mininum code for debugging.

#This command creates a symb link to enable the default site config in Nginx.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
