#!/usr/bin/env bash

# Function to start the manage_my_process program
start_manage_my_process() {
    # Check if the process is already running
    if [ -e /var/run/my_process.pid ]; then
        echo "manage_my_process is already running."
        return
    fi
    
    # Start the program
    /root/alx-system_engineering-devops/0x05-processes_and_signals/manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
}

# Function to stop the manage_my_process program
stop_manage_my_process() {
    if [ -e /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid" 2>/dev/null
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

# Function to restart the manage_my_process program
restart_manage_my_process() {
    stop_manage_my_process > /dev/null 2>&1
    start_manage_my_process > /dev/null 2>&1
    echo "manage_my_process restarted"
}

# Check the arguments and call the appropriate function
case "$1" in
    start)
        start_manage_my_process
        ;;
    stop)
        stop_manage_my_process
        ;;
    restart)
        restart_manage_my_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
