#!/usr/bin/env bash
# Define the PID file location

PID_FILE="/var/run/my_process.pid"

start_process() {
    ./manage_my_process &

    PID=$!

    touch "$PID_FILE"
    echo "$PID" > "$PID_FILE"

    echo "manage_my_process started"
}

stop_process() {
    PID=$(cat "$PID_FILE")

    kill "$PID"

    rm "$PID_FILE"

    echo "manage_my_process stopped"
}

restart_process() {
    PID=$(cat "$PID_FILE")

    kill "$PID"

    rm "$PID_FILE"
	
    ./manage_my_process &

    PID=$!

    touch "$PID_FILE"
    echo "$PID" > "$PID_FILE"

    echo "manage_my_process restarted"
}

case "${1}" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 0
	;;
esac

exit 0
