#!/usr/bin/env bash
# Define the PID file location

PID_FILE="/var/run/my_process.pid"

start_process() {
    ./manage_my_process &

    PID=$!

    touch "$PID_FILE"
    echo "$PID" > "$PID_FILE"

    echo "manage_my_process started"
}

stop_process() {
    PID=(cat "$PID_FILE")

    kill "$PID"

    rm "$PID_FILE"

    echo "manage_my_process stopped"
}

restart_process() {
    stop_process > /dev/null 2>&1

    start_process > /dev/null 2>&1

    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
