#!/usr/bin/env bash
# Display the PID and process name of processes whose name contain the word bash

script_pid=$$

pgrep -f bash | while read -r pid; do
    if [ "$pid" != "$script_pid" ]; then
        echo "$pid bash"
    fi
done
