#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd, showing only the username, user id, and home directory path for each user.

while IFS=':' read -r username _ userid _ homedir _; do
    echo "$username:$userid:$homedir"
done < /etc/passwd
