#!/usr/bin/env bash
# This script displays the content of the current directory in a list format, showing only the part of the name after the first dash

for file in *; do
    case "$file" in
        README.md | *.pub)
            continue ;;
        *)
            echo "${file#*-}" ;;
    esac
done
