#!/usr/bin/env bash
# This script configures the local machine to change the IP address resolution for localhost and facebook.com

cp /etc/hosts ~/hosts.new
echo '127.0.0.2	localhost' > ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
